### ISSUE TITLE
Migrate tests to use the test model on travis, rather than hardcoded flymine. 

### ISSUE THREAD

**Issue by yochannah** [intermine/imcljs#25]
hard-coded live urls is not a great idea for testing; a slow internet day or flymine down will make our tests fail.

**Comment by yochannah** [comment]
This PR needs to be tagged and released: https://github.com/intermine/imcljs/pull/26 now is the time to try it!

**Comment by heralden** [comment]
Resolved by using biotestmine instead, in #45 and #43
