### ISSUE TITLE
[refactor two method names] let's not override class and class? - causes build warnings

### ISSUE THREAD

**Issue by yochannah** [intermine/imcljs#27]
The terminal looks like this when we build bluegenes. Let's just rename these methods to something a little less overridey. Maybe `im-class` and `im-class?` 

Fewer errors = better. 

```bash
WARNING: class already refers to: #'clojure.core/class in namespace: imcljs.path, being replaced by: #'imcljs.path/class
WARNING: class? already refers to: #'clojure.core/class? in namespace: imcljs.path, being replaced by: #'imcljs.path/class?
```

Once this is implemented we'll need to do an update to BlueGenes (possibly) to ensure it's not using these methods directly.

**Comment by yochannah** [comment]
I've added the hacktoberfest label to this issue - it should be a reasonably straightforward refactor if you are comfortable with clojure. BlueGenes, referenced above, is available at https://github.com/intermine/bluegenes, but I _don't_ think you'll need to actually install it or use it if you want to fix this issue. 

The two offending functions are in this file: 

class: https://github.com/intermine/imcljs/blob/dev/src/cljc/imcljs/path.cljc#L99 
class?: https://github.com/intermine/imcljs/blob/dev/src/cljc/imcljs/path.cljc#L143 

## if you want to pick up this task

0. Take a look at the [InterMine contributing guidelines](http://intermine.org/contributing/)
1. Comment on this issue stating that you intend to work on the task
2. When you're ready, add your work to the repo and create a pull request.
### What to do if you need help

Mention @yochannah, tweet [@yoyehudi](http://www.twitter.com/yoyehudi), pop by to say hi on [chat](http://chat.intermine.org) or if needed email yo@intermine.org. Don't forget we're usually only available during uk office hours and will not be able to respond at other times :)

**Comment by BadAlgorithm** [comment]
Hey, I'm happy to take on this issue 😃 

I think there are two options, refactor the names to be prefixed with im-* or simply exclude the clojure functions from the namespace. I think that if the function usages are namespaced when used it should be to go down the excludes route and not have to refactor usages in bluegenes.
